/* Even FIbonacci NUmbers 
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 *                 1, 2,3,5,8,13,21,34,55,89.......
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
 *
 */

#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[]){
  int fib0 = 0 , fib1= 1 , fibn;
  int i = 0;
  long int sum = 0;
  do {
    fibn = fib1 + fib0;
    fib0 = fib1;
    fib1 = fibn;
    if ((fibn % 2) == 0) {
      sum = sum + fibn;
    }
    i++;
  } while( fibn < 4000000);
  printf("%d\n" , sum);
  return EXIT_SUCCESS;
}
